### ISSUE TITLE
Tty color does not get reset for instance info requests

### ISSUE THREAD

**Issue by jmcragun** [slateci/slate-client-server#84] opened 2020-05-13 21:59 UTC
It seems that when using a tty, the color change invoked from a `slate instance info` command does not reset itself until another command changes it back or the connection is broken. Example:

![Screenshot (207)](https://user-images.githubusercontent.com/20020257/81870171-90e43600-9532-11ea-885a-b49b53e7df54.png)
![Screenshot (208)](https://user-images.githubusercontent.com/20020257/81870174-917ccc80-9532-11ea-95e0-768cbb7333c7.png)

Here we see that the text color does not change back to white until several commands later after calling `ls`. We also see that the color _doesn't_ get changed for the first table. An investigation as to why this happens and a fix may be worthwhile.

**Comment by cnweaver** [comment] 2020-05-20 22:26
The only changes the client makes to the terminal's graphics rendition are supposed to be toggling the bold and underline states: https://github.com/slateci/slate-client-server/blob/master/src/client/Client.cpp#L101 . The underlining doesn't seem to be an issue, but the use of bold does. Is it possible that in the examples shown the terminal is configured to make bold text white and regular text green, and also that it uses bold text by default?

We could try reverting the state by using SGR code 0, to reset all attributes, but that might also not have the desired effect depending on how the terminal interprets it.

**Comment by adityavisv** [comment] 2022-01-05 19:29
What terminal/TTY is this?

Apparently, the bold-off code is not universally supported in all terminals. I found [this](https://github.com/curl/curl/blob/3085ccfae996bb0fa606d2c7bc6783dc15d76a30/src/tool_cb_hdr.c#L45-L49) in curl's codebase about ANSI codes for bold and reset. They use the 0 reset code to turn off bold.

**Comment by adityavisv** [comment] 2022-01-25 22:45
Having verified this with the latest release of windows terminal running an SSH session to a CentOS box, I couldn't reproduce it.

It seems Windows Terminal has gotten a bold font rendering fix baked into it some time in August 2021. See [release notes](https://github.com/microsoft/terminal/releases/tag/v1.11.2421.0) of the August release for more information.

Looks like we can close this since it was a bug in the terminal app and not in the slate client.

**Comment by sthapa** [comment] 2023-01-25 21:12
Closing as per last comment

**Closed by sthapa** 2023-01-25 21:12 UTC
Labels: bug, good first issue, client
